function getPokemonList(){
    /* Entrée : aucune
       Sortie : affichage de la liste des pokemons dans l'élément html pokemon-list
       Fonction : Fonction qui permet d'afficher la liste des pokemons dans l'élément html pokemon-list */
    const PokemonList = [
        { number: 1, name: 'Bulbizarre', type: ['Plante', 'Poison'] }, // number : numéro du pokemon, name : nom du pokemon, type : type du pokemon
        { number: 2, name: 'Herbizarre', type: ['Plante', 'Poison'] },
        { number: 3, name: 'Florizarre', type: ['Plante', 'Poison'] },
        { number: 4, name: 'Salamèche', type: ['Feu'] },
        { number: 5, name: 'Reptincel', type: ['Feu'] },
        { number: 6, name: 'Dracaufeu', type: ['Feu', 'Vol'] },
        { number: 7, name: 'Carapuce', type: ['Eau'] },
        { number: 8, name: 'Carabaffe', type: ['Eau'] },
        { number: 9, name: 'Tortank', type: ['Eau'] },
        { number: 10, name: 'Chenipan', type: ['Insecte'] },
        { number: 11, name: 'Chrysacier', type: ['Insecte'] },
        { number: 12, name: 'Papilusion', type: ['Insecte', 'Vol'] },
        { number: 13, name: 'Aspicot', type: ['Insecte', 'Poison'] },
        { number: 14, name: 'Coconfort', type: ['Insecte', 'Poison'] },
        { number: 15, name: 'Dardargnan', type: ['Insecte', 'Poison'] },
        { number: 16, name: 'Roucool', type: ['Normal', 'Vol'] },
        { number: 17, name: 'Roucoups', type: ['Normal', 'Vol'] },
        { number: 18, name: 'Roucarnage', type: ['Normal', 'Vol'] },
        { number: 19, name: 'Rattata', type: ['Normal'] },
        { number: 20, name: 'Rattatac', type: ['Normal'] },
        { number: 21, name: 'Piafabec', type: ['Normal', 'Vol'] },
        { number: 22, name: 'Rapasdepic', type: ['Normal', 'Vol'] },
        { number: 23, name: 'Abo', type: ['Poison'] },
        { number: 24, name: 'Arbok', type: ['Poison'] },
        { number: 25, name: 'Pikachu', type: ['Électrique'] },
        { number: 26, name: 'Raichu', type: ['Électrique'] },
        { number: 27, name: 'Sabelette', type: ['Sol'] },
        { number: 28, name: 'Sablaireau', type: ['Sol'] },
        { number: 29, name: 'Nidoran♀', type: ['Poison'] },
        { number: 30, name: 'Nidorina', type: ['Poison'] },
        { number: 31, name: 'Nidoqueen', type: ['Poison', 'Sol'] },
        { number: 32, name: 'Nidoran♂', type: ['Poison'] },
        { number: 33, name: 'Nidorino', type: ['Poison'] },
        { number: 34, name: 'Nidoking', type: ['Poison', 'Sol'] },
        { number: 35, name: 'Mélofée', type: ['Fée'] },
        { number: 36, name: 'Mélodelfe', type: ['Fée'] },
        { number: 37, name: 'Goupix', type: ['Feu'] },
        { number: 38, name: 'Feunard', type: ['Feu'] },
        { number: 39, name: 'Rondoudou', type: ['Normal', 'Fée'] },
        { number: 40, name: 'Grodoudou', type: ['Normal', 'Fée'] },
        { number: 41, name: 'Nosferapti', type: ['Poison', 'Vol'] },
        { number: 42, name: 'Nosferalto', type: ['Poison', 'Vol'] },
        { number: 43, name: 'Mystherbe', type: ['Plante', 'Poison'] },
        { number: 44, name: 'Ortide', type: ['Plante', 'Poison'] },
        { number: 45, name: 'Rafflesia', type: ['Plante', 'Poison'] },
        { number: 46, name: 'Paras', type: ['Insecte', 'Plante'] },
        { number: 47, name: 'Parasect', type: ['Insecte', 'Plante'] },
        { number: 48, name: 'Mimitoss', type: ['Insecte', 'Poison'] },
        { number: 49, name: 'Aéromite', type: ['Insecte', 'Poison'] },
        { number: 50, name: 'Taupiqueur', type: ['Sol'] },
        { number: 51, name: 'Triopikeur', type: ['Sol'] },
        { number: 52, name: 'Miaouss', type: ['Normal'] },
        { number: 53, name: 'Persian', type: ['Normal'] },
        { number: 54, name: 'Psykokwak', type: ['Eau'] },
        { number: 55, name: 'Akwakwak', type: ['Eau'] },
        { number: 56, name: 'Férosinge', type: ['Combat'] },
        { number: 57, name: 'Colossinge', type: ['Combat'] },
        { number: 58, name: 'Caninos', type: ['Feu'] },
        { number: 59, name: 'Arcanin', type: ['Feu'] },
        { number: 60, name: 'Ptitard', type: ['Eau'] },
        { number: 61, name: 'Têtarte', type: ['Eau'] },
        { number: 62, name: 'Tartard', type: ['Eau', 'Combat'] },
        { number: 63, name: 'Abra', type: ['Psy'] },
        { number: 64, name: 'Kadabra', type: ['Psy'] },
        { number: 65, name: 'Alakazam', type: ['Psy'] },
        { number: 66, name: 'Machoc', type: ['Combat'] },
        { number: 67, name: 'Machopeur', type: ['Combat'] },
        { number: 68, name: 'Mackogneur', type: ['Combat'] },
        { number: 69, name: 'Chétiflor', type: ['Plante', 'Poison'] },
        { number: 70, name: 'Boustiflor', type: ['Plante', 'Poison'] },
        { number: 71, name: 'Empiflor', type: ['Plante', 'Poison'] },
        { number: 72, name: 'Tentacool', type: ['Eau', 'Poison'] },
        { number: 73, name: 'Tentacruel', type: ['Eau', 'Poison'] },
        { number: 74, name: 'Racaillou', type: ['Roche', 'Sol'] },
        { number: 75, name: 'Gravalanch', type: ['Roche', 'Sol'] },
        { number: 76, name: 'Grolem', type: ['Roche', 'Sol'] },
        { number: 77, name: 'Ponyta', type: ['Feu'] },
        { number: 78, name: 'Galopa', type: ['Feu'] },
        { number: 79, name: 'Ramoloss', type: ['Eau', 'Psy'] },
        { number: 80, name: 'Flagadoss', type: ['Eau', 'Psy'] },
        { number: 81, name: 'Magnéti', type: ['Électrique', 'Acier'] },
        { number: 82, name: 'Magnéton', type: ['Électrique', 'Acier'] },
        { number: 83, name: 'Canarticho', type: ['Normal', 'Vol'] },
        { number: 84, name: 'Doduo', type: ['Normal', 'Vol'] },
        { number: 85, name: 'Dodrio', type: ['Normal', 'Vol'] },
        { number: 86, name: 'Otaria', type: ['Eau'] },
        { number: 87, name: 'Lamantine', type: ['Eau', 'Glace'] },
        { number: 88, name: 'Tadmorv', type: ['Poison'] },
        { number: 89, name: 'Grotadmorv', type: ['Poison'] },
        { number: 90, name: 'Kokiyas', type: ['Eau'] },
        { number: 91, name: 'Crustabri', type: ['Eau', 'Glace'] },
        { number: 92, name: 'Fantominus', type: ['Spectre', 'Poison'] },
        { number: 93, name: 'Spectrum', type: ['Spectre', 'Poison'] },
        { number: 94, name: 'Ectoplasma', type: ['Spectre', 'Poison'] },
        { number: 95, name: 'Onix', type: ['Roche', 'Sol'] },
        { number: 96, name: 'Soporifik', type: ['Psy'] },
        { number: 97, name: 'Hypnomade', type: ['Psy'] },
        { number: 98, name: 'Krabby', type: ['Eau'] },
        { number: 99, name: 'Krabboss', type: ['Eau'] },
        { number: 100, name: 'Voltorbe', type: ['Électrique'] },
        { number: 101, name: 'Électrode', type: ['Électrique'] },
        { number: 102, name: 'Noeunoeuf', type: ['Plante', 'Psy'] },
        { number: 103, name: 'Noadkoko', type: ['Plante', 'Psy'] },
        { number: 104, name: 'Osselait', type: ['Sol'] },
        { number: 105, name: 'Ossatueur', type: ['Sol'] },
        { number: 106, name: 'Kicklee', type: ['Combat'] },
        { number: 107, name: 'Tygnon', type: ['Combat'] },
        { number: 108, name: 'Excelangue', type: ['Normal'] },
        { number: 109, name: 'Smogo', type: ['Poison'] },
        { number: 110, name: 'Smogogo', type: ['Poison'] },
        { number: 111, name: 'Rhinocorne', type: ['Sol', 'Roche'] },
        { number: 112, name: 'Rhinoféros', type: ['Sol', 'Roche'] },
        { number: 113, name: 'Leveinard', type: ['Normal'] },
        { number: 114, name: 'Saquedeneu', type: ['Plante'] },
        { number: 115, name: 'Kangourex', type: ['Normal'] },
        { number: 116, name: 'Hypotrempe', type: ['Eau'] },
        { number: 117, name: 'Hypocéan', type: ['Eau'] },
        { number: 118, name: 'Poissirène', type: ['Eau'] },
        { number: 119, name: 'Poissoroy', type: ['Eau'] },
        { number: 120, name: 'Stari', type: ['Eau'] },
        { number: 121, name: 'Staross', type: ['Eau', 'Psy'] },
        { number: 122, name: 'M. Mime', type: ['Psy', 'Fée'] },
        { number: 123, name: 'Insécateur', type: ['Insecte', 'Vol'] },
        { number: 124, name: 'Lippoutou', type: ['Glace', 'Psy'] },
        { number: 125, name: 'Élektek', type: ['Électrique'] },
        { number: 126, name: 'Magmar', type: ['Feu'] },
        { number: 127, name: 'Scarabrute', type: ['Insecte'] },
        { number: 128, name: 'Tauros', type: ['Normal'] },
        { number: 129, name: 'Magicarpe', type: ['Eau'] },
        { number: 130, name: 'Léviator', type: ['Eau', 'Vol'] },
        { number: 131, name: 'Lokhlass', type: ['Eau', 'Glace'] },
        { number: 132, name: 'Métamorph', type: ['Normal'] },
        { number: 133, name: 'Évoli', type: ['Normal'] },
        { number: 134, name: 'Aquali', type: ['Eau'] },
        { number: 135, name: 'Pyroli', type: ['Feu'] },
        { number: 136, name: 'Voltali', type: ['Électrique'] },
        { number: 137, name: 'Porygon', type: ['Normal'] },
        { number: 138, name: 'Amonita', type: ['Roche', 'Eau'] },
        { number: 139, name: 'Amonistar', type: ['Roche', 'Eau'] },
        { number: 140, name: 'Kabuto', type: ['Roche', 'Eau'] },
        { number: 141, name: 'Kabutops', type: ['Roche', 'Eau'] },
        { number: 142, name: 'Ptéra', type: ['Roche', 'Vol'] },
        { number: 143, name: 'Ronflex', type: ['Normal'] },
        { number: 144, name: 'Artikodin', type: ['Glace', 'Vol'] },
        { number: 145, name: 'Électhor', type: ['Électrique', 'Vol'] },
        { number: 146, name: 'Sulfura', type: ['Feu', 'Vol'] },
        { number: 147, name: 'Minidraco', type: ['Dragon'] },
        { number: 148, name: 'Draco', type: ['Dragon'] },
        { number: 149, name: 'Dracolosse', type: ['Dragon', 'Vol'] },
        { number: 150, name: 'Mewtwo', type: ['Psy'] },
        { number: 151, name: 'Mew', type: ['Psy'] },
];
    const pokemonListDiv = document.getElementById('pokemonList');
    const ul = document.createElement('ul');

    PokemonList.forEach(pokemon => {
        const li = document.createElement('li');
        li.textContent = `${pokemon.number}: ${pokemon.name} - ${pokemon.type.join(', ')}`;
        ul.appendChild(li);
    });

    pokemonListDiv.appendChild(ul);
}

getPokemonList();

const pokemonListDiv = document.getElementById('pokemonList');
const img = document.createElement('img');
img.src = 'welcome.jpg';
img.alt = 'WELCOME TO TWIN PEAKS';
img.style.width = '200px';
img.style.height = 'auto';
pokemonListDiv.insertAdjacentElement('afterend', img);

img.addEventListener('click', function() {
    window.location.href = 'https://docs.google.com/document/d/1tyGliCe7tMOj2Ssx03d7LmCjko5Fv42EA-_jwttCQI8/edit?usp=sharing';
});
``


    