function getPokemonList(){
    const PokemonList = [
        { number: 1, name: 'Bulbasaur', type: ['Grass', 'Poison'] },
        { number: 2, name: 'Ivysaur', type: ['Grass', 'Poison'] },
        {number: 3, name: 'Venusaur', type: ['Grass', 'Poison'] },
        { number: 4, name: 'Charmander', type: ['Fire'] },
        { number: 5, name: 'Charmeleon', type: ['Fire'] },
        { number: 6, name: 'Charizard', type: ['Fire', 'Flying'] },
        { number: 7, name: 'Squirtle', type: ['Water'] },
        { number: 8, name: 'Wartortle', type: ['Water'] },
        { number: 9, name: 'Blastoise', type: ['Water'] },
        { number: 10, name: 'Caterpie', type: ['Bug'] },
        { number: 11, name: 'Metapod', type: ['Bug'] },
        { number: 12, name: 'Butterfree', type: ['Bug', 'Flying'] },
        { number: 13, name: 'Weedle', type: ['Bug', 'Poison'] },
        { number: 14, name: 'Kakuna', type: ['Bug', 'Poison'] },
        { number: 15, name: 'Beedrill', type: ['Bug', 'Poison'] },
        { number: 16, name: 'Pidgey', type: ['Normal', 'Flying'] },
        { number: 17, name: 'Pidgeotto', type: ['Normal', 'Flying'] },
        { number: 18, name: 'Pidgeot', type: ['Normal', 'Flying'] },
        { number: 19, name: 'Rattata', type: ['Normal'] },
        { number: 20, name: 'Raticate', type: ['Normal'] },
        { number: 21, name: 'Spearow', type: ['Normal', 'Flying'] },
        { number: 22, name: 'Fearow', type: ['Normal', 'Flying'] },
        { number: 23, name: 'Ekans', type: ['Poison'] },
        { number: 24, name: 'Arbok', type: ['Poison'] },
        { number: 25, name: 'Pikachu', type: ['Electric'] },
        { number: 26, name: 'Raichu', type: ['Electric'] },
        { number: 27, name: 'Sandshrew', type: ['Ground'] },
        { number: 28, name: 'Sandslash', type: ['Ground'] },
        { number: 29, name: 'Nidoran♀', type: ['Poison'] },
        { number: 30, name: 'Nidorina', type: ['Poison'] },
        { number: 31, name: 'Nidoqueen', type: ['Poison', 'Ground'] },
        { number: 32, name: 'Nidoran♂', type: ['Poison'] },
        { number: 33, name: 'Nidorino', type: ['Poison'] },
        { number: 34, name: 'Nidoking', type: ['Poison', 'Ground'] },
        { number: 35, name: 'Clefairy', type: ['Fairy'] },
        { number: 36, name: 'Clefable', type: ['Fairy'] },
        { number: 37, name: 'Vulpix', type: ['Fire'] },
        { number: 38, name: 'Ninetales', type: ['Fire'] },
        { number: 39, name: 'Jigglypuff', type: ['Normal', 'Fairy'] },
        { number: 40, name: 'Wigglytuff', type: ['Normal', 'Fairy'] },
        { number: 41, name: 'Zubat', type: ['Poison', 'Flying'] },
        { number: 42, name: 'Golbat', type: ['Poison', 'Flying'] },
        { number: 43, name: 'Oddish', type: ['Grass', 'Poison'] },
        { number: 44, name: 'Gloom', type: ['Grass', 'Poison'] },
        { number: 45, name: 'Vileplume', type: ['Grass', 'Poison'] },
        { number: 46, name: 'Paras', type: ['Bug', 'Grass'] },
        { number: 47, name: 'Parasect', type: ['Bug', 'Grass'] },
        { number: 48, name: 'Venonat', type: ['Bug', 'Poison'] },
        { number: 49, name: 'Venomoth', type: ['Bug', 'Poison'] },
        { number: 50, name: 'Diglett', type: ['Ground'] },
        { number: 51, name: 'Dugtrio', type: ['Ground'] },
        { number: 52, name: 'Meowth', type: ['Normal'] },
        { number: 53, name: 'Persian', type: ['Normal'] },
        { number: 54, name: 'Psyduck', type: ['Water'] },
        { number: 55, name: 'Golduck', type: ['Water'] },
        { number: 56, name: 'Mankey', type: ['Fighting'] },
        { number: 57, name: 'Primeape', type: ['Fighting'] },
        { number: 58, name: 'Growlithe', type: ['Fire'] },
        { number: 59, name: 'Arcanine', type: ['Fire'] },
        { number: 60, name: 'Poliwag', type: ['Water'] },
        { number: 61, name: 'Poliwhirl', type: ['Water'] },
        { number: 62, name: 'Poliwrath', type: ['Water', 'Fighting'] },
        { number: 63, name: 'Abra', type: ['Psychic'] },
        { number: 64, name: 'Kadabra', type: ['Psychic'] },
        { number: 65, name: 'Alakazam', type: ['Psychic'] },
        { number: 66, name: 'Machop', type: ['Fighting'] },
        { number: 67, name: 'Machoke', type: ['Fighting'] },
        { number: 68, name: 'Machamp', type: ['Fighting'] },
        { number: 69, name: 'Bellsprout', type: ['Grass', 'Poison'] },
        { number: 70, name: 'Weepinbell', type: ['Grass', 'Poison'] },
        { number: 71, name: 'Victreebel', type: ['Grass', 'Poison'] },
        { number: 72, name: 'Tentacool', type: ['Water', 'Poison'] },
        { number: 73, name: 'Tentacruel', type: ['Water', 'Poison'] },
        { number: 74, name: 'Geodude', type: ['Rock', 'Ground'] },
        { number: 75, name: 'Graveler', type: ['Rock', 'Ground'] },
        { number: 76, name: 'Golem', type: ['Rock', 'Ground'] },
        { number: 77, name: 'Ponyta', type: ['Fire'] },
        { number: 78, name: 'Rapidash', type: ['Fire'] },
        { number: 79, name: 'Slowpoke', type: ['Water', 'Psychic'] },
        { number: 80, name: 'Slowbro', type: ['Water', 'Psychic'] },
        { number: 81, name: 'Magnemite', type: ['Electric', 'Steel'] },
        { number: 82, name: 'Magneton', type: ['Electric', 'Steel'] },
        { number: 83, name: 'Farfetch\'d', type: ['Normal', 'Flying'] },
        { number: 84, name: 'Doduo', type: ['Normal', 'Flying'] },
        { number: 85, name: 'Dodrio', type: ['Normal', 'Flying'] },
        { number: 86, name: 'Seel', type: ['Water'] },
        { number: 87, name: 'Dewgong', type: ['Water', 'Ice'] },
        { number: 88, name: 'Grimer', type: ['Poison'] },
        { number: 89, name: 'Muk', type: ['Poison'] },
        { number: 90, name: 'Shellder', type: ['Water'] },
        { number: 91, name: 'Cloyster', type: ['Water', 'Ice'] },
        { number: 92, name: 'Gastly', type: ['Ghost', 'Poison'] },
        { number: 93, name: 'Haunter', type: ['Ghost', 'Poison'] },
        { number: 94, name: 'Gengar', type: ['Ghost', 'Poison'] },
        { number: 95, name: 'Onix', type: ['Rock', 'Ground'] },
        { number: 96, name: 'Drowzee', type: ['Psychic'] },
        { number: 97, name: 'Hypno', type: ['Psychic'] },
        { number: 98, name: 'Krabby', type: ['Water'] },
        { number: 99, name: 'Kingler', type: ['Water'] },
        { number: 100, name: 'Voltorb', type: ['Electric'] },
        { number: 101, name: 'Electrode', type: ['Electric'] },
        { number: 102, name: 'Exeggcute', type: ['Grass', 'Psychic'] },
        { number: 103, name: 'Exeggutor', type: ['Grass', 'Psychic'] },
        { number: 104, name: 'Cubone', type: ['Ground'] },
        { number: 105, name: 'Marowak', type: ['Ground'] },
        { number: 106, name: 'Hitmonlee', type: ['Fighting'] },
        { number: 107, name: 'Hitmonchan', type: ['Fighting'] },
        { number: 108, name: 'Lickitung', type: ['Normal'] },
        { number: 109, name: 'Koffing', type: ['Poison'] },
        { number: 110, name: 'Weezing', type: ['Poison'] },
        { number: 111, name: 'Rhyhorn', type: ['Ground', 'Rock'] },
        { number: 112, name: 'Rhydon', type: ['Ground', 'Rock'] },
        { number: 113, name: 'Chansey', type: ['Normal'] },
        { number: 114, name: 'Tangela', type: ['Grass'] },
        { number: 115, name: 'Kangaskhan', type: ['Normal'] },
        { number: 116, name: 'Horsea', type: ['Water'] },
        { number: 117, name: 'Seadra', type: ['Water'] },
        { number: 118, name: 'Goldeen', type: ['Water'] },
        { number: 119, name: 'Seaking', type: ['Water'] },
        { number: 120, name: 'Staryu', type: ['Water'] },
        { number: 121, name: 'Starmie', type: ['Water', 'Psychic'] },
        { number: 122, name: 'Mr. Mime', type: ['Psychic', 'Fairy'] },
        { number: 123, name: 'Scyther', type: ['Bug', 'Flying'] },
        { number: 124, name: 'Jynx', type: ['Ice', 'Psychic'] },
        { number: 125, name: 'Electabuzz', type: ['Electric'] },
        { number: 126, name: 'Magmar', type: ['Fire'] },
        { number: 127, name: 'Pinsir', type: ['Bug'] },
        { number: 128, name: 'Tauros', type: ['Normal'] },
        { number: 129, name: 'Magikarp', type: ['Water'] },
        { number: 130, name: 'Gyarados', type: ['Water', 'Flying'] },
        { number: 131, name: 'Lapras', type: ['Water', 'Ice'] },
        { number: 132, name: 'Ditto', type: ['Normal'] },
        { number: 133, name: 'Eevee', type: ['Normal'] },
        { number: 134, name: 'Vaporeon', type: ['Water'] },
        { number: 135, name: 'Jolteon', type: ['Electric'] },
        { number: 136, name: 'Flareon', type: ['Fire'] },
        { number: 137, name: 'Porygon', type: ['Normal'] },
        { number: 138, name: 'Omanyte', type: ['Rock', 'Water'] },
        { number: 139, name: 'Omastar', type: ['Rock', 'Water'] },
        { number: 140, name: 'Kabuto', type: ['Rock', 'Water'] },
        { number: 141, name: 'Kabutops', type: ['Rock', 'Water'] },
        { number: 142, name: 'Aerodactyl', type: ['Rock', 'Flying'] },
        { number: 143, name: 'Snorlax', type: ['Normal'] },
        { number: 144, name: 'Articuno', type: ['Ice', 'Flying'] },
        { number: 145, name: 'Zapdos', type: ['Electric', 'Flying'] },
        { number: 146, name: 'Moltres', type: ['Fire', 'Flying'] },
        { number: 147, name: 'Dratini', type: ['Dragon'] },
        { number: 148, name: 'Dragonair', type: ['Dragon'] },
        { number: 149, name: 'Dragonite', type: ['Dragon', 'Flying'] },
        { number: 150, name: 'Mewtwo', type: ['Psychic'] },
        { number: 151, name: 'Mew', type: ['Psychic'] },
    ];
    for (let i = 0; i < PokemonList.length; i++) {
        document.write(`<li>${PokemonList[i].number} : ${PokemonList[i].name} - ${PokemonList[i].type.join(', ')}</li>`);
    }
    document.write('</ul>');
}
getPokemonList();
    